### ISSUE TITLE
Better Error messages from rest api

### ISSUE THREAD

**Issue by Anicodeth** [Anicodeth/BebBlocky-IDE#19]

**Comment by ffekirnew** [comment]
This is half-done in my latest push. In my efforts to enforce the security of the app and make the signin/signup process interactive and clear to users, I have updated the backend (definition of error and central error handling) and the front end (form validation). So The api now returns correct status codes (400 - bad request, 404 - not found...) and relevant message.

**Comment by ffekirnew** [comment]
I can finish it, if you assign it to me.
